"""Users and Posts

Revision ID: 74870c5d9e87
Revises: 
Create Date: 2020-07-27 10:28:40.164948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74870c5d9e87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('friend_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Post')
    op.drop_table('User')
    # ### end Alembic commands ###
